apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kubernetes-manifests-custom
  # --- HPAs Actius ---
  - scalers/frontend-rps.yaml
  - scalers/adservice-rps.yaml
  - scalers/checkoutservice-rps.yaml
  - scalers/currencyservice-rps.yaml
  - scalers/recommendationservice-rps.yaml
  - scalers/cartservice-rps.yaml
  - scalers/emailservice-rps.yaml
  - scalers/paymentservice-rps.yaml

components:
  - ../patches
