{
 "title": "Anàlisi d'escaclat",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Microservei",
    "query": {
     "query": "label_values({namespace=\"default\"},deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Peticions per segon (RPS): $service",
   "type": "timeseries",
   "description": "Total requests in the cluster",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"destination\", destination_workload=\"$service\", namespace=\"default\"}[1m]))",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Nombre de rèpliques: $service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"$service\", namespace=\"default\"}",
     "legendFormat": "Nombre de rèpliques"
    }
   ]
  },
  {
   "title": "Consum de memòria RAM: $service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", pod=~\"$service-.*\", container!=\"\"})",
     "legendFormat": "Consum de memòria RAM"
    }
   ]
  },
  {
   "title": "Ús de CPU: $service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\", pod=~\"$service-.*\"}) ",
     "legendFormat": "Ús de CPU (cores)"
    }
   ]
  },
  {
   "title": "Latència: $service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", destination_workload=\"$service\", namespace=\"default\"}[1m])) by (le))",
     "legendFormat": "Latència P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", destination_workload=\"$service\", namespace=\"default\"}[1m])) by (le))",
     "legendFormat": "Latència P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", destination_workload=\"$service\", namespace=\"default\"}[1m])) by (le))",
     "legendFormat": "Latència P50"
    }
   ]
  }
 ]
}