apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: currencyservice-latency
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: currencyservice
  minReplicaCount: 1
  maxReplicaCount: 20
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 15
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://kube-prom-stack-kube-prome-prometheus.observability.svc.cluster.local:9090 
      metricName: istio_latency_p95
      query: |
        histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{reporter="destination", destination_workload="currencyservice", destination_workload_namespace="default"}[1m])) by (le))
      threshold: '10'