apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kubernetes-manifests-custom
  # --- HPAs Actius ---
  - scalers/frontend-latency.yaml
  - scalers/adservice-latency.yaml
  - scalers/checkoutservice-latency.yaml
  - scalers/currencyservice-latency.yaml
  - scalers/recommendationservice-latency.yaml
  - scalers/cartservice-latency.yaml
  - scalers/emailservice-latency.yaml
  - scalers/paymentservice-latency.yaml

components:
  - ../patches
