apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kubernetes-manifests-custom
  # --- HPAs Actius ---
  - hpa/frontend-hpa.yaml
  - hpa/adservice-hpa.yaml
  - hpa/checkoutservice-hpa.yaml
  - hpa/currencyservice-hpa.yaml
  - hpa/recommendationservice-hpa.yaml
  - hpa/cartservice-hpa.yaml
  - hpa/emailservice-hpa.yaml
  - hpa/paymentservice-hpa.yaml

components:
  - ../patches
